[package]
name = "mofu"
version = "0.1.0"
edition = "2024"
authors = ["Lingxuan Ye <love@lingxuan.io>"]
repository = "https://github.com/Lingxuan-Ye/mofu"
readme = "README.md"
license = "MIT"
description = "More optimistic file utilities."

[dependencies]
serde = "1.0.228"
